// Code generated by MockGen. DO NOT EDIT.
// Source: tmplctlr/kubeclient.go

package tmplctlr_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockKubeClient is a mock of KubeClient interface
type MockKubeClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubeClientMockRecorder
}

// MockKubeClientMockRecorder is the mock recorder for MockKubeClient
type MockKubeClientMockRecorder struct {
	mock *MockKubeClient
}

// NewMockKubeClient creates a new mock instance
func NewMockKubeClient(ctrl *gomock.Controller) *MockKubeClient {
	mock := &MockKubeClient{ctrl: ctrl}
	mock.recorder = &MockKubeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockKubeClient) EXPECT() *MockKubeClientMockRecorder {
	return _m.recorder
}

// Apply mocks base method
func (_m *MockKubeClient) Apply(file string) (string, error) {
	ret := _m.ctrl.Call(_m, "Apply", file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply
func (_mr *MockKubeClientMockRecorder) Apply(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Apply", reflect.TypeOf((*MockKubeClient)(nil).Apply), arg0)
}

// Delete mocks base method
func (_m *MockKubeClient) Delete(file string) (string, error) {
	ret := _m.ctrl.Call(_m, "Delete", file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (_mr *MockKubeClientMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Delete", reflect.TypeOf((*MockKubeClient)(nil).Delete), arg0)
}
